### ISSUE TITLE
Feat: 친구 목록 기본 기능 구현

### ISSUE THREAD

**Issue by mukhoplus** [GoLAB-Project/GoLAB-backend#2]
## Issue: 친구 목록 기본 기능 구현
- Domain에 생성자 추가
- DTO, Repository, Service, Controller 구현

## Description
상기 파일들을 작성하고, **Postman**을 통해 API 테스트 완료했습니다.

## Todo
- [x] FriendList.java에 생성자 추가
- [x] FriendListDTO.java 추가
- [x] FriendListRepository.java
- [x] FriendListService.java 및 FriendListServiceImpl.java 추가
- [x] FriendListController.java
