### ISSUE TITLE
Feat: 차단 목록 기본 기능 구현

### ISSUE THREAD

**Issue by mukhoplus** [GoLAB-Project/GoLAB-backend#4]
## Issue: 차단 목록 기본 기능 구현
- Domain에 생성자 추가
- DTO, Repository, Service, Controller 구현

## Description
상기 파일들을 작성하고, **Postman**을 통해 API 테스트 완료했습니다.

## Todo
- [x] BanList.java에 생성자 추가
- [x] BanListDTO.java 추가
- [x] BanListRepository.java
- [x] BanListService.java 및 BanListServiceImpl.java 추가
- [ ] BanListController.java
