### ISSUE TITLE
Feat: 채팅 관련 기능 구현

### ISSUE THREAD

**Issue by mukhoplus** [GoLAB-Project/GoLAB-backend#9]
## Issue: Feature
채팅

## Description
채팅방 생성, 소켓 서버 및 채팅 전송 관련 기능 구현

## Todo
- [x] 데이터베이스 테이블 수정으로 인한 도메인 수정
- [x] 친구 목록, 차단 목록 쿼리문 수정
- [x] 채팅방 관련 `repository` 작성
- [x] 채팅방 관련 `service` 작성
- [x] 채팅방 관련 `controller` 완성
- [x] `WebSocket` 서버 구축
- [x] 채팅 관련 `repository` 작성(postChat, readChat 등에 이어지는 채팅, 채팅방 업데이트)
- [x] 채팅방 목록, 채팅방 기능 테스트

## ETC
1차적으로 구현 후, 세부적인 기능을 추가할 예정

**Comment by mukhoplus** [comment]
채팅방 관련 코드 작성 완료(아무튼 완료임)

**Comment by mukhoplus** [comment]
프로토타입 `WebSocket 서버`를 구축했습니다.

---

만약 테스트를 원하신다면, 다음 설명을 따라해주세요.

1. 우선 테스트용으로 다음과 같은 파일을 생성해주세요.(저는 `socketTest.js`라고 명명했습니다.)

  ```javascript
  const WebSocket = require('ws');
  
  const socket = new WebSocket('ws://localhost:8080/socket');
  
  socket.onopen = (event) => {
      console.log('웹소켓 연결이 열렸습니다.');
      socket.send('안녕, 서버!');
  };
  
  socket.onmessage = (event) => {
      const receivedMessage = event.data;
      console.log('서버:', receivedMessage);
  };
  
  // 사용자 입력을 받아서 메시지를 전송합니다.
  const readline = require('readline');
  const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
  });
  
  rl.on('line', (input) => {
      socket.send(input); // 입력된 메시지를 서버로 전송합니다.
  });
  ```

3. 해당 js 파일이 있는 디렉토리에서 `npm install ws` 명령어를 실행해주세요.
4. 이후 스프링 서버를 실행하고, `node socketTest`를 실행해주세요. 이때, node 뒤에는 파일명이 들어가야 합니다.
5. 클라이언트를 여러 개 실행하여 텍스트를 입력 및 전송해보세요.

---

- 추후 **코드 분석** 후, 핸들러에 로직 추가가 필요합니다.
- 아마 클라이언트에서 데이터를 `JSON` 형태로 전달하면, 서버에서 데이터를 분석하여 데이터베이스 및 소켓에 원하는 로직을 실행시키는 방식으로 진행 될 것 같습니다.
